[project]
site_url = "https://acceptilation.github.io/botany/"
site_name = "Botany: A Victorian Expedition"
site_description = "A conversion of the official rules from PDF to Markdown"
site_author = "Acceptilation"
copyright = "Botany: A Victorian Expedition by <a href=\"https://duxsomnium.com/\">Dux Somnium</a>"

nav = [
  { "Botany: A Victorian Expedition" = "index.md" },
  { "A Plant Hunter!" = "plant-hunter.md" },
  { "Game Components" = "game-components.md" },
  { "Game Board Setup" = "game-board-setup.md" },
  { "Player Setup" = "player-setup.md" },
  { "Expedition & Character Cards" = "expedition-and-character-cards.md" },
  { "Playing the Game" = "playing-the-game.md" },
  { "Player Turns" = "player-turns.md" },
  { "The Estate Space" = "estate-space.md" },
  { "Ending the Game" = "ending-the-game.md" },
  { "Solo Mode Rules" = "solo-mode.md" }
]

[project.theme]
favicon = "tulip.png"
language = "en"
features = [
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.tracking",
  "search.highlight"
]
logo = "tulip.png"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "pink"
accent = "green"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "pink"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions]
abbr = { }
admonition = { }
attr_list = { }
def_list = { }
footnotes = { }
md_in_html = { }
toc = {
  permalink = true
}
pymdownx.arithmatex = {
  generic = true
}
pymdownx.betterem = { }
pymdownx.caret = { }
pymdownx.details = { }
pymdownx.emoji = {
  emoji_generator = "zensical.extensions.emoji.to_svg",
  emoji_index = "zensical.extensions.emoji.twemoji",
}
pymdownx.highlight = {
  anchor_linenums = true,
  line_spans = "__span",
  pygments_lang_class = true,
}
pymdownx.inlinehilite = { }
pymdownx.keys = { }
pymdownx.magiclink = { }
pymdownx.mark = { }
pymdownx.smartsymbols = { }
# pymdownx.snippets = {
#   base_path = "includes",
# }
pymdownx.superfences = {
  custom_fences = [
    {
      name = "mermaid",
      class = "mermaid",
      format = "pymdownx.superfences.fence_code_format",
    },
  ],
}
pymdownx.tabbed = {
  alternate_style = true,
  combine_header_slug = true
}
pymdownx.tasklist = {
  custom_checkbox = true
}
pymdownx.tilde = { }
